<?php

return [
    'SUCCESS_CODE' => 200,
    'RECORD_CREATED_CODE' => 201,
    'NO_RESULT_CODE' => 204,
    'VALIDATION_ERROR_CODE' => 400,
    'UNAUTHORIZED_CODE' => 401,
    'PERMISSION_CODE' => 403,
    'NO_RECORD_CODE' => 404,
    'FAILED_CODE' => 409,
    'EXCEPTION_ERROR_CODE' => 500,

    'VALIDATION_ERROR_MESSAGE' => 'Invalid request!'
];
